name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/wang/deployment_repos/python_discord_bot

          # stop the old container
          docker compose down

          # fast forward to new code
          git pull origin main

          # Setup env vars
          export DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}
          export OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
          export APP_DATA_DIR=${{secrets.APP_DATA_DIR}}
          export CHATGPT_CHANNEL=${{secrets.CHATGPT_CHANNEL}}
          export PERSONAL_ASSISTANT_CHANNEL=${{secrets.PERSONAL_ASSISTANT_CHANNEL}}

          # build and start new container
          docker compose build
          docker compose up -d --remove-orphans