services:

  discord-bot:
    build: ./
    volumes:
      - discord_bot_data:/app/data
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      APP_DATA_DIR: ${APP_DATA_DIR}
      CHATGPT_CHANNEL: ${CHATGPT_CHANNEL}
      PERSONAL_ASSISTANT_CHANNEL: ${PERSONAL_ASSISTANT_CHANNEL}

volumes:
  discord_bot_data:

