name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build and run
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          APP_DATA_DIR: ${{ secrets.APP_DATA_DIR }}
          CHATGPT_CHANNEL: ${{ secrets.CHATGPT_CHANNEL }}
          PERSONAL_ASSISTANT_CHANNEL: ${{ secrets.PERSONAL_ASSISTANT_CHANNEL }}

        run: |
          docker compose build
          docker compose up -d --remove-orphans
