name: Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/wang/deployment_repos/python_discord_bot
          docker compose down
          git pull origin main

          # Setup env vars
          export DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}}
          export OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
          export APP_DATA_DIR=${{secrets.APP_DATA_DIR}}

          docker compose up